import type { Metadata } from "next";
import "./_styles/index.css";
import { Layout } from "./_layout/layout";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning={true} lang="en">
            <Layout>
                {children}
            </Layout>
        </html>
    );
}
